### ISSUE TITLE
How to run on Linux? 

### ISSUE THREAD

**Issue by danindiana** [sharanyaa/text_classifier#2]
Ubuntu 14.04

Getting an error when trying to install: 

speed@speed-desktop:~/Downloads/nlptxt$ sudo pip3 install https://github.com/sharanyaa/nlp_naivebayes_textclassifier
Downloading/unpacking https://github.com/sharanyaa/nlp_naivebayes_textclassifier
  Downloading nlp_naivebayes_textclassifier (unknown size): 16kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/util.py", line 645, in unpack_file
    and is_svn_page(file_contents(filename))):
  File "/usr/lib/python3/dist-packages/pip/util.py", line 211, in file_contents
    return fp.read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Storing debug log for failure in /home/speed/.pip/pip.log

~~~

**Comment by sharanyaa** [comment]
Try following the steps in report.txt and please let me know if you have any trouble!

**Comment by sharanyaa** [comment]
sorry, i meant report.txt*
